apiVersion: v1
kind: Service
metadata:
  name: web-nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
  selector:
    app.kubernetes.io/name: nginx
